apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awscredentials.aws.compute.hub.appvia.io
spec:
  group: aws.compute.hub.appvia.io
  names:
    kind: AWSCredential
    listKind: AWSCredentialList
    plural: awscredentials
    singular: awscredential
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AWSCredential is the Schema for the awscredentials API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AWSCredentialSpec defines the desired state of AWSCredential
          type: object
        status:
          description: AWSCredentialStatus defines the observed state of AWSCredential
          type: object
        spec:
          description: AWSCredentialsSpec defines the desired state of AWSCredentials
          properties:
            id:
              description: AWS Access Key ID
              type: string
            secret:
              description: AWS Secret Access Key
              type: string
          required:
          - id
          - secret
          type: object
        status:
          description: AWSCredentialsStatus defines the observed state of AWSCredentials
          properties:
            status:
              description: Status provides a overall status
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
